# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: BackDoor Workflow

on:
  push:
    branches: main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: MVN Build
      run: mvn --batch-mode --update-snapshots verify
    - name: Staging
      run: mkdir staging && cp target/*.jar staging
    - name: Upload The Bruh
      uses: actions/upload-artifact@v3
      with:
        name: backdoor-latest
        path: staging
